Issue #4 - Stop using an empty nonce for GCM
nakabonne/pbgopy pull request #11
Opened 2020-12-01 21:35 UTC by name-schema

In crypto/crypto.go
  Used crypto/rand to supply secure random data to fill the nonce
  Created func GetNonce to contain logic for generating the nonce
   given the nonce size
  Removed unused function RandomBytes. The functionality provided
   is simple to replicate if needed in the future. So for now, I'd
   just rather remove the cognative load of just having that there.

In crypto/crypto_test.go
  Removed tests for RandomBytes

2020-12-02 00:34 UTC, nakabonne requested changes

2020-12-02 00:34 UTC, nakabonne commented on crypto/crypto.go
> +func GetNonce(length int) ([]byte, error) {
Let's keep it private until needed!

2020-12-02 00:36 UTC, nakabonne commented
@name-schema Thanks for your contribution! Let me just make one thing clear, just in case. Your commit and your Github account don't seem to be tied to each other:

![image](https://user-images.githubusercontent.com/19730728/100812969-9dee5580-3481-11eb-8bd3-88f448fb4df4.png)

I'd like to welcome you as a contributor, but as it stands, you don't count as a contributor. Would it be possible to authenticate the Github account on your local PC?

After that, feel free to force push.

2020-12-02 04:47 UTC, name-schema commented
I'm not too sure how to sync it. I've only used github casually and have never contributed to another's project before. I've made a change to local configs, lets see if it'll change when I make the updates to the code.

2020-12-03 00:22 UTC, nakabonne approved these changes
Looks neat, and it seems to have been successfully authenticated. Great work!

2020-12-03 00:22 UTC, merged