Issue #5 - Automating Password Entry
nakabonne/pbgopy pull request #12
Opened 2020-12-02 04:53 UTC by name-schema

In commands/copy.go
  Created new function getPasswordFromEnv to work as a fallback
   password if the -p flag is not set. Important to note, the -p
   flag takes priority over the env var, as it should.
  Updated logic to check password length before using it to encrypt

In commands/env.go
  Added new env const:
   const pbgopyPasswordFileEnv = "PBGOPY_PASSWORD_FILE"

In commands/paste.go
  Updated logic to check password length before using it to decrypt

2020-12-03 00:52 UTC, nakabonne commented
Thanks for your contribution! I'm in the middle of something, I'll take a look later!

2020-12-03 09:47 UTC, jcwillox commented
Just an idea, why not store the password in an environment variable like `PBGOPY_TOKEN` or `PBGOPY_PASS`.

2020-12-03 12:35 UTC, nakabonne requested changes

2020-12-03 12:35 UTC, nakabonne commented on commands/copy.go
> +
Please remove the unneeded line.

2020-12-03 12:35 UTC, nakabonne commented on commands/copy.go
> +	if len(password) != 0 {
Why not just compare with "".
```suggestion
	if password != "" {
```

2020-12-03 12:35 UTC, nakabonne commented on commands/copy.go
> +func getPasswordFromEnv(fileLoc string) (string, error) {
nit
```suggestion
func getPasswordFromEnv(filepath string) (string, error) {
```

2020-12-03 12:35 UTC, nakabonne commented on commands/paste.go
> +	if len(password) != 0 {
Here as well:
```suggestion
	if password != "" {
```

2020-12-03 12:39 UTC, nakabonne commented
@name-schema Thank you! Left some comments.

2020-12-03 12:40 UTC, nakabonne commented
@jcwillox Nice idea. Can you open an issue for that?

2020-12-03 13:58 UTC, nakabonne commented
And I'm sorry but could you resolve the conflicts?

2020-12-07 15:12 UTC, name-schema commented
Working on that today, was out of pocket.

2020-12-09 23:27 UTC, nakabonne commented
Thank you! I'm in the middle of something, so will take a look this weekend!

2020-12-13 08:05 UTC, nakabonne approved these changes
Thank you!

2020-12-13 08:05 UTC, merged